
language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:

#build 
  - docker-compose -f docker-compose-build.yaml build --parallel

after_success:
## Tagging
  - docker tag udagram-api-feed daitv3/udagram-api-feed:v1
  - docker tag reverseproxy daitv3/reverseproxy:v1
  - docker tag udagram-api-user daitv3/udagram-api-user:v1
  - docker tag udagram-frontend:local daitv3/udagram-frontend:v1
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push daitv3/reverseproxy:v1
  - docker push daitv3/udagram-api-feed:v1
  - docker push daitv3/udagram-api-user:v1
  - docker push daitv3/udagram-frontend:v1

